# Generated by Django 4.2.24 on 2025-09-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_author_options_alter_bookinstance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/books/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/authors/'),
        ),
    ]
